//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketing
    {
        public int Id_Marketing { get; set; }
        public Nullable<int> ServicioAdquirido { get; set; }
        public Nullable<int> Empresa { get; set; }
        public Nullable<int> Sugerencia { get; set; }
        public string URL { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
        public virtual Servicio Servicio { get; set; }
        public virtual Servicio Servicio1 { get; set; }
    }
}
