//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servidor
    {
        public int Id_Servidor { get; set; }
        public string Direccion_Web { get; set; }
        public string Correo { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> ServicioEmpresa { get; set; }
    
        public virtual ServicioEmpresa ServicioEmpresa1 { get; set; }
    }
}
