//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        public int Id_Usuario { get; set; }
        [Required]
        public string Nombre { get; set; }
        [DisplayName("Primer Apellido")]
        public string Apellido1 { get; set; }
        [DisplayName("Segundo Apellido")]
        public string Apellido2 { get; set; }
        [Required]
        public string Correo { get; set; }
        [Required]
        public string Contraseña { get; set; }
        [DisplayName("Fecha de Creacion")]
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public Nullable<int> Empresa { get; set; }
        [Required]
        public Nullable<int> Rol { get; set; }
        [DisplayName("Empresa")]
        public virtual Empresa Empresa1 { get; set; }
        [DisplayName("Rol")]
        public virtual Rol Rol1 { get; set; }
    }
}
